# Generated by Django 4.1.2 on 2022-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government_Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_crime_title', models.CharField(max_length=30)),
                ('gr_crime_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_crime_title', models.CharField(max_length=30)),
                ('prop_crime_description', models.CharField(max_length=100)),
            ],
        ),
    ]
