# Generated by Django 4.1.2 on 2022-10-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_government_related_property_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPC_Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('section_description', models.CharField(max_length=100)),
                ('section_punishment_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IT_Acts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_title', models.CharField(max_length=100)),
                ('act_description', models.CharField(max_length=100)),
                ('act_punishment_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Judgements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgements_description', models.CharField(max_length=100)),
            ],
        ),
    ]
