# Generated by Django 4.1.2 on 2022-11-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0003_ipc_sections_it_acts_judgements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPC_Sections',
        ),
        migrations.DeleteModel(
            name='Judgements',
        ),
    ]
