# Generated by Django 4.1.2 on 2022-11-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0004_delete_ipc_sections_delete_judgements'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPC_Sections',
            fields=[
                ('section_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('section_title', models.CharField(max_length=100)),
                ('section_description', models.CharField(max_length=100)),
                ('section_punishment_description', models.CharField(max_length=100)),
            ],
        ),
    ]
