# Generated by Django 4.1.2 on 2022-11-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0006_judgements'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_related',
            name='pr_crime_ipc',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.ipc_sections'),
        ),
        migrations.AddField(
            model_name='person_related',
            name='pr_crime_itact',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
    ]
