# Generated by Django 4.1.2 on 2022-11-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0007_person_related_pr_crime_ipc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Judgements',
            new_name='IPC_Judgements',
        ),
        migrations.RenameField(
            model_name='ipc_judgements',
            old_name='judgement_SC',
            new_name='ipc_judgement_SC',
        ),
        migrations.RenameField(
            model_name='ipc_judgements',
            old_name='judgements_description',
            new_name='ipc_judgements_description',
        ),
        migrations.AlterField(
            model_name='person_related',
            name='pr_crime_ipc',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.ipc_sections'),
        ),
        migrations.AlterField(
            model_name='person_related',
            name='pr_crime_itact',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
        migrations.CreateModel(
            name='IT_Judgements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_judgements_description', models.CharField(max_length=100)),
                ('it_judgement_SC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts')),
            ],
        ),
    ]
