# Generated by Django 4.1.2 on 2022-11-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0010_remove_it_judgements_it_judgements_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='government_related',
            name='gr_crime_ipc',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.ipc_sections'),
        ),
        migrations.AddField(
            model_name='government_related',
            name='gr_crime_itact',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
        migrations.AddField(
            model_name='property_related',
            name='prop_crime_ipc',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.ipc_sections'),
        ),
        migrations.AddField(
            model_name='property_related',
            name='prop_crime_itact',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
    ]
