# Generated by Django 4.1.2 on 2022-11-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0011_government_related_gr_crime_ipc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipc_sections',
            name='section_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ipc_sections',
            name='section_punishment_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ipc_sections',
            name='section_title',
            field=models.CharField(max_length=1000),
        ),
    ]
