# Generated by Django 4.1.2 on 2022-11-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0012_alter_ipc_sections_section_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='government_related',
            name='gr_crime_itact',
        ),
        migrations.RemoveField(
            model_name='it_judgements',
            name='it_judgement_SC',
        ),
        migrations.RemoveField(
            model_name='person_related',
            name='pr_crime_itact',
        ),
        migrations.RemoveField(
            model_name='property_related',
            name='prop_crime_itact',
        ),
        migrations.DeleteModel(
            name='IT_Acts',
        ),
    ]
