# Generated by Django 4.1.2 on 2022-11-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0013_remove_government_related_gr_crime_itact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IT_Acts',
            fields=[
                ('act_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('act_title', models.CharField(max_length=1000)),
                ('act_description', models.CharField(max_length=1000)),
                ('act_punishment_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='government_related',
            name='gr_crime_itact',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
        migrations.AddField(
            model_name='it_judgements',
            name='it_judgement_SC',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
        migrations.AddField(
            model_name='person_related',
            name='pr_crime_itact',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
        migrations.AddField(
            model_name='property_related',
            name='prop_crime_itact',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
    ]
