# Generated by Django 4.1.2 on 2022-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0014_it_acts_government_related_gr_crime_itact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_related',
            name='pr_crime_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='person_related',
            name='pr_crime_title',
            field=models.CharField(max_length=1000),
        ),
    ]
