# Generated by Django 4.1.2 on 2022-11-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0015_alter_person_related_pr_crime_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government_related',
            name='gr_crime_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='government_related',
            name='gr_crime_title',
            field=models.CharField(max_length=1000),
        ),
    ]
