# Generated by Django 4.1.2 on 2022-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0016_alter_government_related_gr_crime_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipc_judgements',
            name='ipc_judgements_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ipc_judgements',
            name='ipc_judgements_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='it_judgements',
            name='it_judgements_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='it_judgements',
            name='it_judgements_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
