# Generated by Django 4.1.2 on 2022-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0017_alter_ipc_judgements_ipc_judgements_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government_related',
            name='gr_crime_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='government_related',
            name='gr_crime_title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ipc_judgements',
            name='ipc_judgements_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='ipc_judgements',
            name='ipc_judgements_title',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='ipc_sections',
            name='section_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ipc_sections',
            name='section_punishment_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ipc_sections',
            name='section_title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='it_acts',
            name='act_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='it_acts',
            name='act_punishment_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='it_acts',
            name='act_title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='it_judgements',
            name='it_judgements_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='it_judgements',
            name='it_judgements_title',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='person_related',
            name='pr_crime_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='person_related',
            name='pr_crime_title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='property_related',
            name='prop_crime_description',
            field=models.CharField(max_length=2000),
        ),
    ]
