# Generated by Django 4.1.2 on 2022-11-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0018_alter_government_related_gr_crime_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government_related',
            name='gr_crime_ipc',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.ipc_sections'),
        ),
        migrations.AlterField(
            model_name='government_related',
            name='gr_crime_itact',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
    ]
