# Generated by Django 4.1.2 on 2022-11-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0019_alter_government_related_gr_crime_ipc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_related',
            name='pr_crime_ipc',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.ipc_sections'),
        ),
        migrations.AlterField(
            model_name='person_related',
            name='pr_crime_itact',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
        migrations.AlterField(
            model_name='property_related',
            name='prop_crime_ipc',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.ipc_sections'),
        ),
        migrations.AlterField(
            model_name='property_related',
            name='prop_crime_itact',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tables.it_acts'),
        ),
    ]
